[package]
name = "basic_server_rust"
version = "0.1.0"
authors = ["Bolin <clement.bolin@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
